name: num_remap
description: An implementation for the “Arduino map” function in Dart, which allows numbers to be remapped from one range to another.
version: 1.0.0
repository: https://github.com/Adrian-Samoticha/num_remap
issue_tracker: https://github.com/Adrian-Samoticha/num_remap/issues

environment:
  sdk: '>=2.17.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
